from __future__ import annotations

from typing import Protocol, runtime_checkable

from module_system.controller.admin.permission.vo.menu.menu_list_req_vo import MenuListReqVO
from module_system.controller.admin.permission.vo.menu.menu_save_vo import MenuSaveVO
from module_system.dal.dataobject.permission.menu_do import MenuDO


@runtime_checkable
class MenuService(Protocol):
    async def create_menu(self, create_req_vo: MenuSaveVO) -> int: ...

    async def update_menu(self, update_req_vo: MenuSaveVO) -> None: ...

    async def update_status(self, menu_id: int, status: int) -> None: ...

    async def delete_menu(self, menu_id: int) -> None: ...

    async def delete_menu_batch(self, menu_ids: list[int]) -> int: ...

    async def filter_disable_menus(self, menu_list: list[MenuDO]) -> list[MenuDO]: ...

    async def get_menu_id_list_by_permission_from_cache(self, permission: str) -> list[int]: ...

    async def get_menu(self, menu_id: int) -> MenuDO | None: ...

    async def get_menu_list_by_req(self, req: MenuListReqVO | None = None) -> list[MenuDO]: ...

    async def get_menu_list(self) -> list[MenuDO]: ...

    async def validate_parent_menu(self, parent_id: int | None, child_id: int | None) -> None: ...

    async def validate_menu(
        self, parent_id: int | None, name: str, menu_id: int | None
    ) -> None: ...

    def init_menu_property(self, menu: MenuDO) -> None: ...

    async def get_menu_list_by_ids(self, ids: set[int]) -> list[MenuDO]: ...

    async def get_menu_ids_by_permissions(self, permissions: set[str]) -> dict[str, list[int]]: ...
