from typing import Protocol, runtime_checkable


@runtime_checkable
class PermissionCacheService(Protocol):
    async def invalidate_role_caches(self) -> None: ...
    async def invalidate_menu_caches(self) -> None: ...
    async def invalidate_user_caches(self) -> None: ...
    async def invalidate_all(self) -> None: ...
