from __future__ import annotations

from typing import Protocol, runtime_checkable

from framework.starter_data_permission.public import (
    DataScopeRule,
)
from framework.starter_security.public import (
    PermissionSnapshot,
)
from module_system.api.permission.dto.dept_data_permission_resp_dto import DeptDataPermissionRespDTO
from module_system.controller.admin.permission.vo.permission.permission_assign_role_data_scope_req_vo import (
    PermissionAssignRoleDataScopeReqVO,
)


@runtime_checkable
class PermissionService(Protocol):
    async def has_any_permissions(self, user_id: int, *permissions: str) -> bool: ...

    async def has_any_permission(self, roles, permission: str) -> bool: ...

    async def has_any_roles(self, user_id: int, *roles: str) -> bool: ...

    async def get_role_menu_list_by_role_id(self, role_id: int) -> set[int]: ...

    async def get_role_menu_list_by_role_ids(self, role_ids) -> set[int]: ...

    async def get_menu_role_id_list_by_menu_id_from_cache(self, menu_id: int) -> set[int]: ...

    async def assign_user_role(self, user_id: int, role_ids: set[int]) -> None: ...

    async def get_user_role_id_list_by_user_id(self, user_id: int) -> set[int]: ...

    async def get_user_role_id_list_by_user_id_from_cache(self, user_id: int) -> set[int]: ...

    async def get_enable_user_role_list_by_user_id_from_cache(self, user_id: int): ...

    async def assign_role_data_scope(self, req: PermissionAssignRoleDataScopeReqVO) -> None: ...

    async def get_dept_data_permission(self, user_id: int) -> DeptDataPermissionRespDTO: ...

    async def assign_role_menu(self, role_id: int, menu_ids: set[int]) -> None: ...

    async def process_menu_deleted(self, menu_id: int) -> None: ...

    async def process_role_deleted(self, role_id: int) -> None: ...

    async def process_user_deleted(self, user_id: int) -> None: ...

    async def get_user_role_id_list_by_role_id(self, role_ids) -> set[int]: ...

    async def get_user_menu_list_by_user_id_from_cache(self, user_id: int) -> set[int]: ...

    async def authorization_revision(self, session) -> str: ...

    async def permission_snapshot(self, session, *, binding: str) -> PermissionSnapshot: ...

    async def data_rules(self, session) -> tuple[DataScopeRule, ...]: ...

    async def department_descendants(self, session, department_id: str) -> frozenset[str]: ...

    async def department_users(self, session, department_ids: frozenset[str]) -> frozenset[str]: ...
