from __future__ import annotations

from typing import Any, Collection, Protocol, runtime_checkable

from framework.common.page import PageResult
from module_system.controller.admin.permission.vo.role.role_page_req_vo import RolePageReqVO
from module_system.controller.admin.permission.vo.role.role_save_req_vo import RoleSaveReqVO
from module_system.dal.cache.permission.dto.role_cache_dto import RoleCacheDTO
from module_system.dal.dataobject.permission.role_do import RoleDO


@runtime_checkable
class RoleService(Protocol):
    async def create_role(
        self, create_req_vo: RoleSaveReqVO, builtin: int | None = None
    ) -> int: ...

    async def update_role(self, update_req_vo: RoleSaveReqVO) -> None: ...

    async def delete_role(self, id: int) -> None: ...

    async def delete_role_batch(self, ids: list[int]) -> int: ...

    async def validate_role_duplicate(self, name: str, code: str, role_id: int | None) -> None: ...

    async def validate_role_for_update(self, role_id: int) -> Any: ...

    async def get_role(self, role_id: int) -> Any: ...

    async def get_role_from_cache(self, role_id: int) -> RoleCacheDTO | None: ...

    async def get_role_list_by_status(self, statuses: Collection[int]) -> list[RoleDO]: ...

    async def get_role_list_by_ids(self, ids: Collection[int]) -> list[RoleDO]: ...

    async def get_role_list_from_cache(self, ids: Collection[int]) -> list[RoleDO]: ...

    async def get_role_page(self, req_vo: RolePageReqVO) -> PageResult[RoleDO]: ...

    async def validate_role_list(self, ids: Collection[int]) -> None: ...

    async def update_role_data_scope(
        self, role_id: int, data_scope: int, data_scope_dept_ids: set[int]
    ) -> None: ...

    async def has_any_super_admin(self, ids: Collection[int]) -> bool: ...

    async def get_role_list(self) -> list[RoleDO]: ...

    async def update_role_status(self, id: int, status: int) -> None: ...
