from __future__ import annotations

from typing import Collection, Protocol, runtime_checkable

from framework.common.page import PageResult
from module_system.controller.admin.auth.vo.auth_register_req_vo import AuthRegisterReqVO
from module_system.controller.admin.user.vo.profile.profile_update_req_vo import (
    UserProfileUpdateReqVO,
)
from module_system.controller.admin.user.vo.user.user_import_excel_vo import UserImportExcelVO
from module_system.controller.admin.user.vo.user.user_import_resp_vo import UserImportRespVO
from module_system.controller.admin.user.vo.user.user_page_req_vo import UserPageReqVO
from module_system.controller.admin.user.vo.user.user_save_req_vo import UserSaveReqVO
from module_system.dal.dataobject.user.admin_user_do import AdminUserDO
from module_system.framework.notification.model.notification_recipient import NotificationRecipient


@runtime_checkable
class AdminUserService(Protocol):
    async def create_user(self, create_req_vo: UserSaveReqVO) -> int: ...

    async def register_user(self, register_req_vo: AuthRegisterReqVO) -> int: ...

    async def update_user(self, update_req_vo: UserSaveReqVO) -> None: ...

    async def update_user_login(self, id: int, login_ip: str) -> None: ...

    async def update_user_profile(self, id: int, req_vo: UserProfileUpdateReqVO) -> None: ...

    async def update_user_password(self, id: int, password: str) -> None: ...

    async def delete_user(self, id: int) -> None: ...

    async def delete_user_batch(self, ids: list[int]) -> int: ...

    async def get_user_by_username(self, username: str) -> AdminUserDO | None: ...

    async def get_user_by_mobile(self, mobile: str) -> AdminUserDO | None: ...

    async def get_user_page(self, req_vo: UserPageReqVO) -> PageResult[AdminUserDO]: ...

    async def get_user(self, id: int) -> AdminUserDO | None: ...

    async def get_user_list_by_dept_ids(self, dept_ids: Collection[int]) -> list[AdminUserDO]: ...

    async def get_user_list_by_post_ids(self, post_ids: Collection[int]) -> list[AdminUserDO]: ...

    async def get_user_list(self, ids: Collection[int]) -> list[AdminUserDO]: ...

    async def validate_user_list(self, ids: Collection[int]) -> None: ...

    async def get_user_list_by_nickname(self, nickname: str) -> list[AdminUserDO]: ...

    async def is_password_match(self, raw_password: str, encoded_password: str) -> bool: ...

    async def import_user_list(
        self, import_users: list[UserImportExcelVO], is_update_support: bool
    ) -> UserImportRespVO: ...

    async def get_user_list_by_status(self, status: int) -> list[AdminUserDO]: ...

    async def get_user_count(self) -> int: ...

    async def get_user_info_list_by_ids(self, ids: list[int]) -> list[NotificationRecipient]: ...

    async def search_by_keyword(self, keyword: str, limit: int = 20) -> list[AdminUserDO]: ...

    async def change_password(self, user_id: int, password: str): ...

    async def update_user_password_by_vo(self, id, req_vo): ...

    async def update_user_status(self, id, status): ...
