listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=077
chroot_local_user=YES
allow_writeable_chroot=YES
pam_service_name=vsftpd
secure_chroot_dir=/var/run/vsftpd/empty
pasv_enable=YES
pasv_addr_resolve=YES
pasv_min_port=12100
pasv_max_port=12110
xferlog_enable=NO
log_ftp_protocol=NO
