import importlib

import pytest
from pydantic import ValidationError

from module_system.definitions.constants.error_code_constants import ErrorCodeConstants

ENUMS = [
    ("module_system.definitions.enums.common.common_sex_enum", "CommonSexEnum", "MALE", (1, "男")),
    (
        "module_system.definitions.enums.common.common_sex_enum",
        "CommonSexEnum",
        "FEMALE",
        (2, "女"),
    ),
    (
        "module_system.definitions.enums.common.common_sex_enum",
        "CommonSexEnum",
        "UNKNOWN",
        (0, "未知"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGIN_USERNAME",
        (1, "使用账号登录"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGIN_SOCIAL",
        (2, "使用社交登录"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGIN_MOBILE",
        (3, "使用手机登陆"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGIN_SMS",
        (4, "使用短信登陆"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGOUT_SELF",
        (20, "自己主动登出"),
    ),
    (
        "module_system.definitions.enums.logger.login_log_type_enum",
        "LoginLogTypeEnum",
        "LOGOUT_DELETE",
        (21, "强制退出"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "SUCCESS",
        (0, "成功"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "BAD_CREDENTIALS",
        (10, "账号或密码不正确"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "USER_DISABLED",
        (20, "用户被禁用"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "CAPTCHA_NOT_FOUND",
        (30, "验证码不存在"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "CAPTCHA_CODE_ERROR",
        (31, "验证码不正确"),
    ),
    (
        "module_system.definitions.enums.logger.logger_login_result_enum",
        "LoggerLoginResultEnum",
        "UNKNOWN_EXCEPTION",
        (100, "未知异常"),
    ),
    (
        "module_system.definitions.enums.mail.mail_send_status_enum",
        "MailSendStatusEnum",
        "INIT",
        (0, "初始化"),
    ),
    (
        "module_system.definitions.enums.mail.mail_send_status_enum",
        "MailSendStatusEnum",
        "SUCCESS",
        (10, "发送成功"),
    ),
    (
        "module_system.definitions.enums.mail.mail_send_status_enum",
        "MailSendStatusEnum",
        "FAILURE",
        (20, "发送失败"),
    ),
    (
        "module_system.definitions.enums.mail.mail_send_status_enum",
        "MailSendStatusEnum",
        "IGNORE",
        (30, "忽略，即不发送"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_category_enum",
        "AnnouncementCategoryEnum",
        "SYSTEM_MAINTENANCE",
        (1, "系统维护通知"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_category_enum",
        "AnnouncementCategoryEnum",
        "FEATURE_RELEASE",
        (2, "新功能发布"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_category_enum",
        "AnnouncementCategoryEnum",
        "POLICY_CHANGE",
        (3, "重要政策变更"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_priority_enum",
        "AnnouncementPriorityEnum",
        "LOW",
        (1, "低"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_priority_enum",
        "AnnouncementPriorityEnum",
        "MEDIUM",
        (2, "中"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_priority_enum",
        "AnnouncementPriorityEnum",
        "HIGH",
        (3, "高"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_status_enum",
        "AnnouncementStatusEnum",
        "DRAFT",
        (0, "草稿"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_status_enum",
        "AnnouncementStatusEnum",
        "WAIT_PUBLISH",
        (1, "待发布"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_status_enum",
        "AnnouncementStatusEnum",
        "PUBLISHED",
        (2, "已发布"),
    ),
    (
        "module_system.definitions.enums.announcement.announcement_status_enum",
        "AnnouncementStatusEnum",
        "EXPIRED",
        (3, "已过期"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "INTERNAL",
        ("INTERNAL", "站内信"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "IM",
        ("IM", "IM 私聊"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "SMS",
        ("SMS", "短信"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "MAIL",
        ("MAIL", "邮件"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "WECHAT",
        ("WECHAT", "微信公众号"),
    ),
    (
        "module_system.definitions.enums.notification.notification_channel_enum",
        "NotificationChannelEnum",
        "DINGTALK",
        ("DINGTALK", "钉钉"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_status_enum",
        "NoticePushStatusEnum",
        "PUSHING",
        (0, "推送中"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_status_enum",
        "NoticePushStatusEnum",
        "ALL_SUCCESS",
        (1, "全部成功"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_status_enum",
        "NoticePushStatusEnum",
        "PARTIAL_FAIL",
        (2, "部分失败"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_status_enum",
        "NoticePushStatusEnum",
        "ALL_FAILED",
        (3, "全部失败"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_target_type_enum",
        "NoticePushTargetTypeEnum",
        "USER",
        (1, "按用户"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_target_type_enum",
        "NoticePushTargetTypeEnum",
        "DEPT",
        (2, "按部门"),
    ),
    (
        "module_system.definitions.enums.notification.notice_push_target_type_enum",
        "NoticePushTargetTypeEnum",
        "MIXED",
        (3, "混合"),
    ),
    (
        "module_system.definitions.enums.notification.notice_type_enum",
        "NoticeTypeEnum",
        "SYSTEM",
        (1, "系统通知"),
    ),
    (
        "module_system.definitions.enums.notification.notice_type_enum",
        "NoticeTypeEnum",
        "USER",
        (2, "用户通知"),
    ),
    (
        "module_system.definitions.enums.notification.notice_type_enum",
        "NoticeTypeEnum",
        "TASK",
        (3, "任务通知"),
    ),
    (
        "module_system.definitions.enums.notification.notice_type_enum",
        "NoticeTypeEnum",
        "MESSAGE",
        (4, "消息通知"),
    ),
    (
        "module_system.definitions.enums.notification.notice_type_enum",
        "NoticeTypeEnum",
        "ALERT",
        (5, "警告通知"),
    ),
    (
        "module_system.definitions.enums.oauth2.oauth2_grant_type_enum",
        "OAuth2GrantTypeEnum",
        "PASSWORD",
        ("password", "密码模式"),
    ),
    (
        "module_system.definitions.enums.oauth2.oauth2_grant_type_enum",
        "OAuth2GrantTypeEnum",
        "AUTHORIZATION_CODE",
        ("authorization_code", "授权码模式"),
    ),
    (
        "module_system.definitions.enums.oauth2.oauth2_grant_type_enum",
        "OAuth2GrantTypeEnum",
        "IMPLICIT",
        ("implicit", "简化模式"),
    ),
    (
        "module_system.definitions.enums.oauth2.oauth2_grant_type_enum",
        "OAuth2GrantTypeEnum",
        "CLIENT_CREDENTIALS",
        ("client_credentials", "客户端模式"),
    ),
    (
        "module_system.definitions.enums.oauth2.oauth2_grant_type_enum",
        "OAuth2GrantTypeEnum",
        "REFRESH_TOKEN",
        ("refresh_token", "刷新模式"),
    ),
    (
        "framework.starter_data_permission.public",
        "DataScope",
        "ALL",
        (1, "全部数据权限"),
    ),
    (
        "framework.starter_data_permission.public",
        "DataScope",
        "DEPT_CUSTOM",
        (2, "指定部门数据权限"),
    ),
    (
        "framework.starter_data_permission.public",
        "DataScope",
        "DEPT_ONLY",
        (3, "部门数据权限"),
    ),
    (
        "framework.starter_data_permission.public",
        "DataScope",
        "DEPT_AND_CHILD",
        (4, "部门及以下数据权限"),
    ),
    (
        "framework.starter_data_permission.public",
        "DataScope",
        "SELF",
        (5, "仅本人数据权限"),
    ),
    (
        "module_system.definitions.enums.permission.menu_type_enum",
        "MenuTypeEnum",
        "DIR",
        (1, "目录"),
    ),
    (
        "module_system.definitions.enums.permission.menu_type_enum",
        "MenuTypeEnum",
        "MENU",
        (2, "菜单"),
    ),
    (
        "module_system.definitions.enums.permission.menu_type_enum",
        "MenuTypeEnum",
        "BUTTON",
        (3, "按钮"),
    ),
    (
        "module_system.definitions.enums.permission.menu_type_enum",
        "MenuTypeEnum",
        "DATA",
        (4, "数据"),
    ),
    (
        "module_system.definitions.enums.permission.role_code_enum",
        "RoleCodeEnum",
        "SUPER_ADMIN",
        ("super_admin", "超级管理员"),
    ),
    (
        "module_system.definitions.enums.permission.role_code_enum",
        "RoleCodeEnum",
        "CRM_ADMIN",
        ("crm_admin", "CRM 管理员"),
    ),
    (
        "module_system.definitions.enums.permission.role_type_enum",
        "RoleTypeEnum",
        "SYSTEM",
        (1, "内置角色"),
    ),
    (
        "module_system.definitions.enums.permission.role_type_enum",
        "RoleTypeEnum",
        "CUSTOM",
        (2, "自定义角色"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "ADMIN_SMS_LOGIN",
        ("admin-sms-login", "后台用户-手机号登录"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "USER_SMS_LOGIN",
        ("user-sms-login", "会员用户-手机号登陆"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "USER_UPDATE_MOBILE",
        ("user-update-mobile", "会员用户-修改手机"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "USER_UPDATE_PASSWORD",
        ("user-update-password", "会员用户-修改密码"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "USER_RESET_PASSWORD",
        ("user-reset-password", "会员用户-忘记密码"),
    ),
    (
        "module_system.definitions.enums.sms.sms_builtin_template_code_enum",
        "SmsBuiltinTemplateCodeEnum",
        "SYSTEM_NOTICE",
        ("system-notice", "系统通知"),
    ),
    (
        "module_system.definitions.enums.sms.sms_receive_status_enum",
        "SmsReceiveStatusEnum",
        "INIT",
        (0, "初始化"),
    ),
    (
        "module_system.definitions.enums.sms.sms_receive_status_enum",
        "SmsReceiveStatusEnum",
        "SUCCESS",
        (10, "接收成功"),
    ),
    (
        "module_system.definitions.enums.sms.sms_receive_status_enum",
        "SmsReceiveStatusEnum",
        "FAILURE",
        (20, "接收失败"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "MEMBER_LOGIN",
        (1, "会员用户 - 手机号登陆", "user-sms-login"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "MEMBER_UPDATE_MOBILE",
        (2, "会员用户 - 修改手机", "user-update-mobile"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "MEMBER_UPDATE_PASSWORD",
        (3, "会员用户 - 修改密码", "user-update-password"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "MEMBER_RESET_PASSWORD",
        (4, "会员用户 - 忘记密码", "user-reset-password"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "ADMIN_MEMBER_LOGIN",
        (21, "后台用户 - 手机号登录", "admin-sms-login"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "ADMIN_MEMBER_REGISTER",
        (22, "后台用户 - 手机号注册", "admin-sms-register"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "ADMIN_MEMBER_RESET_PASSWORD",
        (23, "后台用户 - 忘记密码", "admin-reset-password"),
    ),
    (
        "module_system.definitions.enums.sms.sms_scene_enum",
        "SmsSceneEnum",
        "ADMIN_MEMBER_UPDATE_MOBILE",
        (24, "后台用户 - 绑定手机号", "admin-update-mobile"),
    ),
    (
        "module_system.definitions.enums.sms.sms_send_status_enum",
        "SmsSendStatusEnum",
        "INIT",
        (0, "初始化"),
    ),
    (
        "module_system.definitions.enums.sms.sms_send_status_enum",
        "SmsSendStatusEnum",
        "SUCCESS",
        (10, "发送成功"),
    ),
    (
        "module_system.definitions.enums.sms.sms_send_status_enum",
        "SmsSendStatusEnum",
        "FAILURE",
        (20, "发送失败"),
    ),
    (
        "module_system.definitions.enums.sms.sms_send_status_enum",
        "SmsSendStatusEnum",
        "IGNORE",
        (30, "忽略，即不发送"),
    ),
    (
        "module_system.definitions.enums.sms.sms_template_type_enum",
        "SmsTemplateTypeEnum",
        "VERIFICATION_CODE",
        (1, "验证码"),
    ),
    (
        "module_system.definitions.enums.sms.sms_template_type_enum",
        "SmsTemplateTypeEnum",
        "NOTICE",
        (2, "通知"),
    ),
    (
        "module_system.definitions.enums.sms.sms_template_type_enum",
        "SmsTemplateTypeEnum",
        "PROMOTION",
        (3, "营销"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "ALIPAY",
        (10, "ALIPAY"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "DINGTALK",
        (20, "DINGTALK"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "WECHAT_ENTERPRISE",
        (30, "WECHAT_ENTERPRISE"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "WECHAT_MP",
        (31, "WECHAT_MP"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "WECHAT_OPEN",
        (32, "WECHAT_OPEN"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "WECHAT_MINI_PROGRAM",
        (33, "WECHAT_MINI_PROGRAM"),
    ),
    (
        "module_system.definitions.enums.social.social_type_enum",
        "SocialTypeEnum",
        "WECHAT_ENTERPRISE_V2",
        (34, "WECHAT_ENTERPRISE_V2"),
    ),
]

MODELS = [
    (
        "module_system.dal.dataobject.dept.dept_do",
        "DeptDO",
        ["name", "parent_id", "sort", "leader_user_id", "phone", "email", "status"],
    ),
    (
        "module_system.dal.dataobject.dept.post_do",
        "PostDO",
        ["code", "name", "sort", "status", "remark"],
    ),
    ("module_system.dal.dataobject.dept.dept_user_post_do", "UserPostDO", ["user_id", "post_id"]),
    (
        "module_system.dal.dataobject.dict.dict_data_do",
        "DictDataDO",
        [
            "sort",
            "label",
            "value",
            "dict_type",
            "status",
            "color_type",
            "tag_style",
            "permission",
            "remark",
        ],
    ),
    (
        "module_system.dal.dataobject.dict.dict_type_do",
        "DictTypeDO",
        ["name", "type", "status", "remark", "deleted_time"],
    ),
    (
        "module_system.dal.dataobject.logger.login_log_do",
        "LoginLogDO",
        [
            "log_type",
            "trace_id",
            "user_id",
            "user_type",
            "username",
            "result",
            "user_ip",
            "user_agent",
        ],
    ),
    (
        "module_system.dal.dataobject.logger.operate_log_do",
        "OperateLogDO",
        [
            "trace_id",
            "user_id",
            "user_type",
            "type",
            "sub_type",
            "biz_id",
            "action",
            "extra",
            "request_method",
            "request_url",
            "user_ip",
            "user_agent",
            "user_info",
        ],
    ),
    (
        "module_system.dal.dataobject.mail.mail_account_do",
        "MailAccountDO",
        ["mail", "username", "password", "host", "port", "ssl_enable", "starttls_enable"],
    ),
    (
        "module_system.dal.dataobject.mail.mail_log_do",
        "MailLogDO",
        [
            "user_id",
            "user_type",
            "to_mail",
            "cc_mail",
            "bcc_mail",
            "account_id",
            "from_mail",
            "template_id",
            "template_code",
            "template_nickname",
            "template_title",
            "template_content",
            "template_params",
            "send_status",
            "send_time",
            "send_message_id",
            "send_exception",
        ],
    ),
    (
        "module_system.dal.dataobject.mail.mail_template_do",
        "MailTemplateDO",
        [
            "name",
            "code",
            "account_id",
            "nickname",
            "title",
            "content",
            "params",
            "status",
            "remark",
        ],
    ),
    (
        "module_system.dal.dataobject.announcement.announcement_do",
        "AnnouncementDO",
        [
            "title",
            "content",
            "status",
            "is_top",
            "sort",
            "category",
            "publish_time",
            "expire_time",
            "publisher",
        ],
    ),
    (
        "module_system.dal.dataobject.notification.notice_do",
        "NoticeDO",
        [
            "code",
            "builtin",
            "title",
            "content",
            "type",
            "user_type",
            "channels",
            "sms_template_code",
            "mail_account_id",
            "publisher",
            "status",
        ],
    ),
    (
        "module_system.dal.dataobject.notification.notice_log_do",
        "NoticeLogDO",
        [
            "notice_id",
            "notice_title",
            "notice_type",
            "push_target_type",
            "target_user_ids",
            "target_dept_ids",
            "target_dept_names",
            "push_channels",
            "total_count",
            "success_count",
            "fail_count",
            "push_status",
            "publisher_info",
        ],
    ),
    (
        "module_system.dal.dataobject.notification.notice_message_do",
        "NoticeMessageDO",
        [
            "user_id",
            "user_type",
            "notice_id",
            "notice_log_id",
            "notice_title",
            "notice_content",
            "notice_type",
            "publisher_info",
            "sent_channels",
            "read_status",
            "read_time",
        ],
    ),
    (
        "module_system.dal.dataobject.oauth2.oauth2_access_token_do",
        "OAuth2AccessTokenDO",
        [
            "user_id",
            "user_type",
            "user_info",
            "scopes",
            "token_digest",
            "refresh_token_id",
            "client_id",
            "expires_time",
        ],
    ),
    (
        "module_system.dal.dataobject.oauth2.oauth2_approve_do",
        "OAuth2ApproveDO",
        ["user_id", "user_type", "client_id", "scope", "approved", "expires_time"],
    ),
    (
        "module_system.dal.dataobject.oauth2.oauth2_client_do",
        "OAuth2ClientDO",
        [
            "client_id",
            "secret",
            "name",
            "logo",
            "description",
            "status",
            "user_type",
            "access_token_validity_seconds",
            "refresh_token_validity_seconds",
            "redirect_uris",
            "authorized_grant_types",
            "scopes",
            "auto_approve_scopes",
            "authorities",
            "resource_ids",
            "additional_information",
        ],
    ),
    (
        "module_system.dal.dataobject.oauth2.oauth2_code_do",
        "OAuth2CodeDO",
        [
            "user_id",
            "user_type",
            "code_digest",
            "client_id",
            "scopes",
            "expires_time",
            "redirect_uri",
            "state",
        ],
    ),
    (
        "module_system.dal.dataobject.oauth2.oauth2_refresh_token_do",
        "OAuth2RefreshTokenDO",
        ["user_id", "token_digest", "user_type", "client_id", "scopes", "expires_time"],
    ),
    (
        "module_system.dal.dataobject.permission.menu_do",
        "MenuDO",
        [
            "name",
            "permission",
            "kind",
            "sort",
            "parent_id",
            "path",
            "icon",
            "component",
            "component_name",
            "status",
            "visible",
            "keep_alive",
            "always_show",
        ],
    ),
    (
        "module_system.dal.dataobject.permission.role_do",
        "RoleDO",
        [
            "name",
            "code",
            "sort",
            "data_scope",
            "data_scope_dept_ids",
            "builtin",
            "status",
            "remark",
        ],
    ),
    (
        "module_system.dal.dataobject.permission.role_menu_do",
        "RoleMenuDO",
        ["role_id", "menu_id"],
    ),
    (
        "module_system.dal.dataobject.permission.permission_user_role_do",
        "UserRoleDO",
        ["user_id", "role_id"],
    ),
    (
        "module_system.dal.dataobject.sms.sms_channel_do",
        "SmsChannelDO",
        ["signature", "code", "status", "remark", "api_key", "api_secret", "callback_url"],
    ),
    (
        "module_system.dal.dataobject.sms.sms_code_do",
        "SmsCodeDO",
        ["mobile", "code", "create_ip", "scene", "today_index", "used", "used_time", "used_ip"],
    ),
    (
        "module_system.dal.dataobject.sms.sms_log_do",
        "SmsLogDO",
        [
            "channel_id",
            "channel_code",
            "template_id",
            "template_code",
            "template_type",
            "template_content",
            "template_params",
            "api_template_id",
            "mobile",
            "user_id",
            "user_type",
            "send_status",
            "send_time",
            "api_send_code",
            "api_send_msg",
            "api_request_id",
            "api_serial_no",
            "receive_status",
            "receive_time",
            "api_receive_code",
            "api_receive_msg",
        ],
    ),
    (
        "module_system.dal.dataobject.sms.sms_template_do",
        "SmsTemplateDO",
        [
            "type",
            "builtin",
            "status",
            "code",
            "name",
            "content",
            "params",
            "remark",
            "api_template_id",
            "channel_id",
            "channel_code",
        ],
    ),
    (
        "module_system.dal.dataobject.social.social_client_do",
        "SocialClientDO",
        [
            "name",
            "social_type",
            "user_type",
            "client_id",
            "client_secret",
            "agent_id",
            "auth_config",
            "status",
        ],
    ),
    (
        "module_system.dal.dataobject.social.social_user_bind_do",
        "SocialUserBindDO",
        ["user_id", "user_type", "social_type", "social_user_id"],
    ),
    (
        "module_system.dal.dataobject.social.social_user_do",
        "SocialUserDO",
        [
            "type",
            "openid",
            "token",
            "raw_token_info",
            "nickname",
            "avatar",
            "raw_user_info",
            "code",
            "state",
        ],
    ),
    (
        "module_system.dal.dataobject.user.admin_user_do",
        "AdminUserDO",
        [
            "username",
            "password",
            "nickname",
            "remark",
            "dept_id",
            "post_ids",
            "email",
            "mobile",
            "sex",
            "avatar",
            "status",
            "login_ip",
            "login_date",
        ],
    ),
    (
        "module_system.dal.dataobject.user.admin_user_profile_do",
        "AdminUserProfileDO",
        [
            "user_id",
            "bio",
            "tags",
            "address",
            "skills",
            "work_scope",
            "expertise",
            "communication_style",
            "ai_preference",
        ],
    ),
]

ERRORS = [
    ("AUTH_LOGIN_BAD_CREDENTIALS", 1002000000, "system.auth.login_bad_credentials"),
    ("AUTH_LOGIN_USER_DISABLED", 1002000001, "system.auth.login_user_disabled"),
    ("AUTH_LOGIN_CAPTCHA_CODE_ERROR", 1002000004, "system.auth.login_captcha_code_error"),
    ("AUTH_THIRD_LOGIN_NOT_BIND", 1002000005, "system.auth.third_login_not_bind"),
    ("AUTH_TOKEN_EXPIRED", 1002000006, "system.auth.token_expired"),
    ("AUTH_MOBILE_NOT_EXISTS", 1002000007, "system.auth.mobile_not_exists"),
    ("AUTH_REGISTER_CAPTCHA_CODE_ERROR", 1002000008, "system.auth.register_captcha_code_error"),
    ("AUTH_INVALID_TOKEN_CODE", 1002000009, "system.auth.invalid_token_code"),
    ("AUTH_TOKEN_NOT_FOUND_CODE", 1002000010, "system.auth.token_not_found"),
    ("MENU_NAME_DUPLICATE", 1002001000, "system.menu.name_duplicate"),
    ("MENU_PARENT_NOT_EXISTS", 1002001001, "system.menu.parent_not_exists"),
    ("MENU_PARENT_ERROR", 1002001002, "system.menu.parent_error"),
    ("MENU_NOT_EXISTS", 1002001003, "system.menu.not_exists"),
    ("MENU_EXISTS_CHILDREN", 1002001004, "system.menu.exists_children"),
    ("MENU_PARENT_NOT_DIR_OR_MENU", 1002001005, "system.menu.parent_not_dir_or_menu"),
    ("MENU_EXISTS_CHILDREN_MENU", 1002001006, "system.menu.exists_children_menu"),
    ("ROLE_NOT_EXISTS", 1002002000, "system.role.not_exists"),
    ("ROLE_NAME_DUPLICATE", 1002002001, "system.role.name_duplicate"),
    ("ROLE_CODE_DUPLICATE", 1002002002, "system.role.code_duplicate"),
    ("ROLE_CAN_NOT_UPDATE_SYSTEM_TYPE_ROLE", 1002002003, "system.role.can_not_update_system_type"),
    ("ROLE_IS_DISABLE", 1002002004, "system.role.is_disable"),
    ("ROLE_ADMIN_CODE_ERROR", 1002002005, "system.role.admin_code_error"),
    ("USER_USERNAME_EXISTS", 1002003000, "system.user.username_exists"),
    ("USER_MOBILE_EXISTS", 1002003001, "system.user.mobile_exists"),
    ("USER_EMAIL_EXISTS", 1002003002, "system.user.email_exists"),
    ("USER_NOT_EXISTS", 1002003003, "system.user.not_exists"),
    ("USER_IMPORT_LIST_IS_EMPTY", 1002003004, "system.user.import_list_is_empty"),
    ("USER_PASSWORD_FAILED", 1002003005, "system.user.password_failed"),
    ("USER_IS_DISABLE", 1002003006, "system.user.is_disable"),
    ("USER_TYPE_NOT_EXISTS", 1002003007, "system.user.type_not_exists"),
    ("USER_IMPORT_INIT_PASSWORD", 1002003009, "system.user.import_init_password"),
    ("USER_MOBILE_NOT_EXISTS", 1002003010, "system.user.mobile_not_exists"),
    ("USER_REGISTER_DISABLED", 1002003011, "system.user.register_disabled"),
    ("USER_KICKOUT_DEVICE_NOT_OWNER", 1002003012, "system.user.kickout_device_not_owner"),
    ("DEPT_NAME_DUPLICATE", 1002004000, "system.dept.name_duplicate"),
    ("DEPT_PARENT_NOT_EXITS", 1002004001, "system.dept.parent_not_exists"),
    ("DEPT_NOT_FOUND", 1002004002, "system.dept.not_found"),
    ("DEPT_EXITS_CHILDREN", 1002004003, "system.dept.exists_children"),
    ("DEPT_PARENT_ERROR", 1002004004, "system.dept.parent_error"),
    ("DEPT_EXISTS_USER", 1002004005, "system.dept.exists_user"),
    ("DEPT_NOT_ENABLE", 1002004006, "system.dept.not_enable"),
    ("DEPT_PARENT_IS_CHILD", 1002004007, "system.dept.parent_is_child"),
    ("POST_NOT_FOUND", 1002005000, "system.post.not_found"),
    ("POST_NOT_ENABLE", 1002005001, "system.post.not_enable"),
    ("POST_NAME_DUPLICATE", 1002005002, "system.post.name_duplicate"),
    ("POST_CODE_DUPLICATE", 1002005003, "system.post.code_duplicate"),
    ("DICT_TYPE_NOT_EXISTS", 1002006001, "system.dict_type.not_exists"),
    ("DICT_TYPE_NOT_ENABLE", 1002006002, "system.dict_type.not_enable"),
    ("DICT_TYPE_NAME_DUPLICATE", 1002006003, "system.dict_type.name_duplicate"),
    ("DICT_TYPE_TYPE_DUPLICATE", 1002006004, "system.dict_type.type_duplicate"),
    ("DICT_TYPE_HAS_CHILDREN", 1002006005, "system.dict_type.has_children"),
    ("DICT_DATA_NOT_EXISTS", 1002007001, "system.dict_data.not_exists"),
    ("DICT_DATA_NOT_ENABLE", 1002007002, "system.dict_data.not_enable"),
    ("DICT_DATA_VALUE_DUPLICATE", 1002007003, "system.dict_data.value_duplicate"),
    ("NOTICE_NOT_FOUND", 1002008001, "system.notice.not_found"),
    ("NOTICE_NOT_ENABLE", 1002008002, "system.notice.not_enable"),
    ("NOTICE_CAN_NOT_UPDATE_SYSTEM_TYPE", 1002008003, "system.notice.can_not_update_system_type"),
    ("ANNOUNCEMENT_NOT_FOUND", 1002008010, "system.announcement.not_found"),
    ("ANNOUNCEMENT_STATUS_ERROR", 1002008011, "system.announcement.status_error"),
    ("ANNOUNCEMENT_PUBLISH_TIME_REQUIRED", 1002008012, "system.announcement.publish_time_required"),
    ("ANNOUNCEMENT_PUBLISH_TIME_INVALID", 1002008013, "system.announcement.publish_time_invalid"),
    ("SMS_CHANNEL_NOT_EXISTS", 1002011000, "system.sms_channel.not_exists"),
    ("SMS_CHANNEL_DISABLE", 1002011001, "system.sms_channel.disable"),
    ("SMS_CHANNEL_HAS_CHILDREN", 1002011002, "system.sms_channel.has_children"),
    ("SMS_SCENE_NOT_FOUND", 1002011003, "system.sms_channel.scene_not_found"),
    ("SMS_TEMPLATE_NOT_EXISTS", 1002012000, "system.sms_template.not_exists"),
    ("SMS_TEMPLATE_CODE_DUPLICATE", 1002012001, "system.sms_template.code_duplicate"),
    ("SMS_TEMPLATE_API_ERROR", 1002012002, "system.sms_template.api_error"),
    ("SMS_TEMPLATE_API_AUDIT_CHECKING", 1002012003, "system.sms_template.api_audit_checking"),
    ("SMS_TEMPLATE_API_AUDIT_FAIL", 1002012004, "system.sms_template.api_audit_fail"),
    ("SMS_TEMPLATE_API_NOT_FOUND", 1002012005, "system.sms_template.api_not_found"),
    ("SMS_TEMPLATE_API_AUDIT_UNKNOWN", 1002012006, "system.sms_template.api_audit_unknown"),
    (
        "SMS_TEMPLATE_CAN_NOT_UPDATE_BUILTIN",
        1002012007,
        "system.sms_template.can_not_update_builtin",
    ),
    ("SMS_SEND_MOBILE_NOT_EXISTS", 1002013000, "system.sms_send.mobile_not_exists"),
    ("SMS_SEND_MOBILE_TEMPLATE_PARAM_MISS", 1002013001, "system.sms_send.template_param_miss"),
    ("SMS_SEND_TEMPLATE_NOT_EXISTS", 1002013002, "system.sms_send.template_not_exists"),
    ("SMS_SEND_MOBILE_INVALID", 1002013003, "system.sms_send.mobile_invalid"),
    ("SMS_CODE_NOT_FOUND", 1002014000, "system.sms_code.not_found"),
    ("SMS_CODE_EXPIRED", 1002014001, "system.sms_code.expired"),
    ("SMS_CODE_USED", 1002014002, "system.sms_code.used"),
    ("SMS_CODE_NOT_CORRECT", 1002014003, "system.sms_code.not_correct"),
    (
        "SMS_CODE_EXCEED_SEND_MAXIMUM_QUANTITY_PER_DAY",
        1002014004,
        "system.sms_code.exceed_send_max_per_day",
    ),
    ("SMS_CODE_SEND_TOO_FAST", 1002014005, "system.sms_code.send_too_fast"),
    ("OAUTH2_CLIENT_NOT_EXISTS", 1002020000, "system.oauth2_client.not_exists"),
    ("OAUTH2_CLIENT_EXISTS", 1002020001, "system.oauth2_client.exists"),
    ("OAUTH2_CLIENT_DISABLE", 1002020002, "system.oauth2_client.disable"),
    (
        "OAUTH2_CLIENT_AUTHORIZED_GRANT_TYPE_NOT_EXISTS",
        1002020003,
        "system.oauth2_client.grant_type_not_exists",
    ),
    ("OAUTH2_CLIENT_SCOPE_OVER", 1002020004, "system.oauth2_client.scope_over"),
    (
        "OAUTH2_CLIENT_REDIRECT_URI_NOT_MATCH",
        1002020005,
        "system.oauth2_client.redirect_uri_not_match",
    ),
    ("OAUTH2_CLIENT_CLIENT_SECRET_ERROR", 1002020006, "system.oauth2_client.client_secret_error"),
    ("OAUTH2_GRANT_CLIENT_ID_MISMATCH", 1002021000, "system.oauth2_grant.client_id_mismatch"),
    ("OAUTH2_GRANT_REDIRECT_URI_MISMATCH", 1002021001, "system.oauth2_grant.redirect_uri_mismatch"),
    ("OAUTH2_GRANT_STATE_MISMATCH", 1002021002, "system.oauth2_grant.state_mismatch"),
    (
        "OAUTH2_GRANT_CLIENT_USER_TYPE_MISMATCH",
        1002021003,
        "system.oauth2_grant.client_user_type_mismatch",
    ),
    ("OAUTH2_GRANT_CLIENT_NOT_CLIENT_TYPE", 1002021004, "system.oauth2_grant.not_client_type"),
    ("OAUTH2_CODE_NOT_EXISTS", 1002022000, "system.oauth2_code.not_exists"),
    ("OAUTH2_CODE_EXPIRE", 1002022001, "system.oauth2_code.expire"),
    ("MAIL_ACCOUNT_NOT_EXISTS", 1002023000, "system.mail_account.not_exists"),
    (
        "MAIL_ACCOUNT_RELATE_TEMPLATE_EXISTS",
        1002023001,
        "system.mail_account.relate_template_exists",
    ),
    ("MAIL_TEMPLATE_NOT_EXISTS", 1002024000, "system.mail_template.not_exists"),
    ("MAIL_TEMPLATE_CODE_EXISTS", 1002024001, "system.mail_template.code_exists"),
    ("MAIL_SEND_TEMPLATE_PARAM_MISS", 1002025000, "system.mail_send.template_param_miss"),
    ("MAIL_SEND_MAIL_NOT_EXISTS", 1002025001, "system.mail_send.mail_not_exists"),
    ("NOTICE_TEMPLATE_NOT_EXISTS", 1002026000, "system.notice_template.not_exists"),
    ("NOTICE_TEMPLATE_CODE_DUPLICATE", 1002026001, "system.notice_template.code_duplicate"),
    ("NOTICE_SEND_TEMPLATE_PARAM_MISS", 1002028000, "system.notice_send.template_param_miss"),
    ("NOTICE_SEND_BATCH_PARAM_MISMATCH", 1002028001, "system.notice_send.batch_param_mismatch"),
    ("NOTICE_SEND_USER_NOT_EXISTS", 1002028002, "system.notice_send.user_not_exists"),
    ("NOTICE_SEND_TEMPLATE_DISABLED", 1002028003, "system.notice_send.template_disabled"),
    ("SDK_CHANNEL_NOT_FOUND", 1002029000, "system.sdk.channel_not_found"),
    ("CAPTCHA_TYPE_INVALID", 1002030001, "system.captcha.type_invalid"),
    ("CAPTCHA_NOT_FOUND_OR_EXPIRED", 1002030002, "system.captcha.not_found_or_expired"),
    ("CAPTCHA_VERIFICATION_FAILED", 1002030003, "system.captcha.verification_failed"),
    ("CAPTCHA_SERVICE_UNAVAILABLE", 1002030004, "system.captcha.service_unavailable"),
    ("CAPTCHA_VERIFICATION_FREQUENT", 1002030005, "system.captcha.verification_frequent"),
    ("CAPTCHA_FAILED_TOO_MANY_ATTEMPTS", 1002030006, "system.captcha.failed_too_many_attempts"),
    ("CAPTCHA_VERIFICATION_PARAM_MISS", 1002030007, "system.captcha.verification_param_miss"),
    ("IP_AREA_NOT_FOUND", 1002031000, "system.ip_area.not_found"),
    ("SOCIAL_CLIENT_NOT_EXISTS", 1002032000, "system.social.client_not_exists"),
    ("SOCIAL_CLIENT_NOT_SUPPORTED", 1002032001, "system.social.client_not_supported"),
    ("SOCIAL_CLIENT_UNIQUE", 1002032002, "system.social.client_unique"),
    ("SOCIAL_CLIENT_AUTH_FAILURE", 1002032003, "system.social.client_auth_failure"),
    ("SOCIAL_USER_AUTH_FAILURE", 1002032004, "system.social.user_auth_failure"),
    ("SOCIAL_USER_NOT_FOUND", 1002032005, "system.social.user_not_found"),
    (
        "SOCIAL_WECHAT_MP_JS_SDK_SIGNATURE_ERROR",
        1002032006,
        "system.social.wechat_mp_js_sdk_signature_error",
    ),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_PHONE_CODE_ERROR",
        1002032007,
        "system.social.weixin_mini_app_phone_code_error",
    ),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_QRCODE_ERROR",
        1002032008,
        "system.social.weixin_mini_app_qrcode_error",
    ),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_SUBSCRIBE_TEMPLATE_ERROR",
        1002032009,
        "system.social.weixin_mini_app_subscribe_template_error",
    ),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_SUBSCRIBE_MESSAGE_ERROR",
        1002032010,
        "system.social.weixin_mini_app_subscribe_message_error",
    ),
    ("SOCIAL_PLATFORM_NOT_EXIST", 1002032011, "system.social.platform_not_exist"),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_ORDER_SHIPPING_ERROR",
        1002032012,
        "system.social.weixin_mini_app_order_shipping_error",
    ),
    (
        "SOCIAL_CLIENT_WEIXIN_MINI_APP_ORDER_CONFIRM_RECEIVE_ERROR",
        1002032013,
        "system.social.weixin_mini_app_order_confirm_receive_error",
    ),
    (
        "SOCIAL_CLIENT_AUTH_CONFIG_INVALID",
        1002032014,
        "system.social.client_auth_config_invalid",
    ),
]


@pytest.mark.parametrize("module, cls, member, expected", ENUMS)
def test_enum_codes_labels_and_extensions(module, cls, member, expected):
    value = getattr(getattr(importlib.import_module(module), cls), member)
    assert (value.code, value.label) == expected[:2]
    if len(expected) == 3:
        assert value.template_code == expected[2]


@pytest.mark.parametrize("module, cls, expected", MODELS)
def test_source_business_fields_have_model_destinations(module, cls, expected):
    model = getattr(importlib.import_module(module), cls)
    assert set(expected) <= set(model.__table__.columns.keys())
    assert model.__table__.comment


def test_error_codes_and_declared_messages():
    assert len({code for _, code, _ in ERRORS}) == len(ERRORS)
    for name, code, key in ERRORS:
        error = getattr(ErrorCodeConstants, name)
        assert error.code == code and error.message_key == key
        assert isinstance(error.description, str) and error.description


def test_web_id_and_enum_validation():
    from module_system.controller.admin.dept.vo.dept.dept_save_req_vo import DeptSaveReqVO
    from module_system.controller.admin.user.vo.user.user_save_req_vo import UserSaveReqVO

    valid = {"name": "研发部", "parentId": "0", "sort": 0, "status": 1}
    assert DeptSaveReqVO.model_validate(valid).parent_id == 0
    for value in (True, 2, "1"):
        with pytest.raises(ValidationError):
            DeptSaveReqVO.model_validate({**valid, "status": value})
    for value in (100, "001", "-1", "9223372036854775808"):
        with pytest.raises(ValidationError):
            DeptSaveReqVO.model_validate({**valid, "id": value})
    with pytest.raises(ValidationError):
        UserSaveReqVO.model_validate({"username": "validname", "nickname": "用户"})
