from typing import Protocol

from module_infra.api.config.dto.config_group_dto import ConfigGroupDTO


class ConfigApi(Protocol):
    async def get_value(self, module: str, key: str) -> str | None: ...

    async def get_values_by_type(self, module: str, type_code: str) -> dict[str, str]: ...

    async def get_all_by_module(self, module: str) -> dict[str, str]: ...

    async def get_grouped_configs(self, module: str) -> list[ConfigGroupDTO]: ...

    async def update_value(self, module: str, key: str, value: str) -> None: ...

    async def batch_update_values(self, module: str, items: list[tuple[str, str]]) -> None: ...
