from __future__ import annotations

from typing import Collection, Protocol, runtime_checkable

from module_system.controller.admin.dept.vo.dept.dept_list_req_vo import DeptListReqVO
from module_system.controller.admin.dept.vo.dept.dept_save_req_vo import DeptSaveReqVO
from module_system.dal.dataobject.dept.dept_do import DeptDO


@runtime_checkable
class DeptService(Protocol):
    async def create_dept(self, create_req_vo: DeptSaveReqVO) -> int: ...

    async def update_dept(self, update_req_vo: DeptSaveReqVO) -> None: ...

    async def update_status(self, dept_id: int, status: int) -> None: ...

    async def delete_dept(self, id: int) -> None: ...

    async def delete_dept_batch(self, ids: list[int]) -> int: ...

    async def get_dept(self, dept_id: int) -> DeptDO | None: ...

    async def get_dept_list_by_ids(self, ids: Collection[int]) -> list[DeptDO]: ...

    async def get_dept_list(self, req_vo: DeptListReqVO) -> list[DeptDO]: ...

    async def get_child_dept_list(self, id: int) -> list[DeptDO]: ...

    async def get_dept_list_by_leader_user_id(self, user_id: int) -> list[DeptDO]: ...

    async def get_dept_list_by_status(self, status: int) -> list[DeptDO]: ...

    async def validate_dept_list(self, ids: Collection[int]) -> None: ...

    async def get_dept_map(self, ids: Collection[int]) -> dict[int, DeptDO]: ...

    async def get_child_dept_list_by_ids(self, ids: Collection[int]) -> list[DeptDO]: ...

    async def get_child_dept_id_list_from_cache(self, id: int) -> set[int]: ...
