from typing import Protocol

from framework.starter_job.model.job_definition import JobDefinition


class JobDefinitionProvider(Protocol):
    """业务定义权威；读主库，写入加入调用方 Database 事务，不提前提交。"""

    async def list_definitions(self) -> tuple[JobDefinition, ...]: ...
    async def get_definition(self, job_id: str) -> JobDefinition | None: ...
    async def save_definition(self, definition: JobDefinition) -> None: ...
    async def delete_definition(self, job_id: str) -> None: ...
    async def stop_definition(self, job_id: str, revision: str) -> None:
        """仅停止匹配版本，不能覆盖执行期间已更新的业务定义。"""
        ...
