from __future__ import annotations

from typing import Collection, Protocol, runtime_checkable

from framework.common.page import PageResult
from module_system.controller.admin.dict.vo.data.data_page_req_vo import DictDataPageReqVO
from module_system.controller.admin.dict.vo.data.data_save_req_vo import DictDataSaveReqVO
from module_system.dal.dataobject.dict.dict_data_do import DictDataDO


@runtime_checkable
class DictDataService(Protocol):
    async def get_dict_data_list(self, status: int, dict_type: str | None) -> list[DictDataDO]: ...

    async def get_dict_data(self, id: int) -> DictDataDO | None: ...

    async def get_dict_data_page(
        self, page_req_vo: DictDataPageReqVO
    ) -> PageResult[DictDataDO]: ...

    async def create_dict_data(self, create_req_vo: DictDataSaveReqVO) -> int: ...

    async def update_dict_data(self, update_req_vo: DictDataSaveReqVO) -> None: ...

    async def update_status(self, dict_data_id: int, status: int) -> None: ...

    async def delete_dict_data(self, id: int) -> None: ...

    async def delete_dict_data_batch(self, ids: list[int]) -> int: ...

    async def get_dict_data_count_by_dict_type(self, dict_type: str) -> int: ...

    async def validate_dict_data_list(self, dict_type: str, values: Collection[str]) -> None: ...

    async def get_dict_data_by_value(self, dict_type: str, value: str) -> DictDataDO | None: ...

    async def parse_dict_data(self, dict_type: str, label: str) -> DictDataDO | None: ...

    async def get_dict_data_list_by_dict_type(self, dict_type: str) -> list[DictDataDO]: ...

    async def get_dict_data_list_by_dict_types(self, dict_types: list[str]) -> list[DictDataDO]: ...
